version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: my-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_USER: user
      MYSQL_PASSWORD: userpass
      MYSQL_DATABASE: userdatabase
    ports:
      - "3306:3306"
    networks:
      - my_network
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

      
  backend:
    build:
      context: ./backend
    container_name: my-backend-container
    ports:
      - "8000:8000"
    networks:
      - my_network
    depends_on:
      mysql:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
    container_name: my-frontend-container
    ports:
      - "80:80"
    networks:
      - my_network
    depends_on:
      mysql:
        condition: service_healthy

networks:
  my_network:
    driver: bridge

volumes:
  mysql_data: