name: pipeline for test environment - backend

# on:
#   pull_request:
#     branches:
#       - Test

on:
  release:
    types: [published]
    
permissions: 
  contents: read
  pull-requests: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code  
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - name: Configure Docker to use Google Cloud credentials
        run: |
          gcloud auth configure-docker europe-west1-docker.pkg.dev

      - name: Start database VM instance
        run: |
          gcloud compute instances start mysql-test --zone=europe-west1-d

      - name: Get database VM public IP
        id: get_ip
        run: |
          IP_ADDRESS=$(gcloud compute instances describe mysql-test \
                       --zone=europe-west1-d \
                       --format='get(networkInterfaces[0].accessConfigs[0].natIP)')
          echo "DATABASE_URL=$IP_ADDRESS" >> $GITHUB_ENV

      - name: change database URL
        run: |
          echo "hello world"

      - name: Build test backend Docker image 
        run: |   
          IMAGE_NAME="europe-west1-docker.pkg.dev/buzzwatch-422510/mutualism/mutualism-backend"  
          TAG="2" 
          docker build -t "$IMAGE_NAME:$TAG" backend

      - name: Push test backend Docker image to GCR
        run: |
          IMAGE_NAME="europe-west1-docker.pkg.dev/buzzwatch-422510/mutualism/mutualism-backend-test"  
          TAG="2" 
          docker push "$IMAGE_NAME:$TAG"

      - name: 'deploy test backend'
        uses: 'google-github-actions/deploy-cloudrun@v2'
        with:
          service: 'mutualism-backend'
          region: 'europe-west1'
          image: 'europe-west1-docker.pkg.dev/buzzwatch-422510/mutualism/mutualism-backend-test:2'

     